package com.dwell.domain.cases.entity;

import com.dwell.domain.building.entity.Building;
import com.dwell.domain.cases.enums.AffectedArea;
import com.dwell.domain.cases.enums.CaseStage;
import com.dwell.domain.cases.enums.Visibility;
import com.dwell.domain.user.entity.User;
import com.dwell.global.common.BaseTimeEntity;
import com.dwell.global.common.LocalizedText;
import com.dwell.global.common.enums.AnalysisStatus;
import com.dwell.global.common.enums.IssueCategory;
import com.dwell.global.common.enums.IssueType;
import com.dwell.global.common.enums.Location;
import com.dwell.global.common.enums.Severity;
import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Map;

@Getter
@Entity
@Table(name = "cases") // "case" is a reserved word, so use "cases"
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Case extends BaseTimeEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // e.g. C-004, sequential per user
    @Column(nullable = false, length = 20)
    private String caseNumber;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    // Used to aggregate live neighbor issues
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "building_id")
    private Building building;

    // Snapshot at creation time
    @Column(length = 20)
    private String unit;

    @Column(nullable = false, length = 100)
    private String title;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private IssueCategory issueCategory;

    // Detail value under issue_category (full list pending), OTHER allowed
    @Column(nullable = false, length = 30)
    private String issueDetail;

    // Required when issue_detail is OTHER
    @Column(length = 50)
    private String issueDetailOther;

    // Aggregated from evidence analysis
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private IssueType issueType;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private Location location;

    // Required when location is OTHER
    @Column(length = 50)
    private String locationOther;

    // e.g. CEILING
    @Column(length = 20)
    private String subLocation;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private AffectedArea affectedArea;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 10)
    private Severity severity;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private CaseStage stage;

    // Only PUBLIC cases count toward building signals
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 10)
    private Visibility visibility = Visibility.PRIVATE;

    @Column(length = 500)
    private String description;

    @Column(nullable = false)
    private boolean safetyAcknowledged;

    // Discovered date
    private LocalDate firstObservedAt;

    private LocalDateTime resolvedAt;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 10)
    private AnalysisStatus analysisStatus;

    // {findings:[{en,native}], recommended_type, alternatives:[type]}
    @JdbcTypeCode(SqlTypes.JSON)
    private Map<String, Object> aiAnalysis;

    // Regenerated when evidence or status changes
    @JdbcTypeCode(SqlTypes.JSON)
    private LocalizedText summary;

    private LocalDateTime summaryUpdatedAt;

    @Column(length = 30)
    private String nextActionType;

    // {title, description, cta}, generated by the Case Agent on stage transitions
    @JdbcTypeCode(SqlTypes.JSON)
    private Map<String, Object> nextAction;

    // Soft delete
    private LocalDateTime deletedAt;

    @Builder
    public Case(String caseNumber, User user, Building building, String unit, String title,
                IssueCategory issueCategory, String issueDetail, String issueDetailOther, IssueType issueType,
                Location location, String locationOther, AffectedArea affectedArea, Severity severity,
                CaseStage stage, Visibility visibility, String description, boolean safetyAcknowledged,
                LocalDate firstObservedAt, AnalysisStatus analysisStatus) {
        this.caseNumber = caseNumber;
        this.user = user;
        this.building = building;
        this.unit = unit;
        this.title = title;
        this.issueCategory = issueCategory;
        this.issueDetail = issueDetail;
        this.issueDetailOther = issueDetailOther;
        this.issueType = issueType;
        this.location = location;
        this.locationOther = locationOther;
        this.affectedArea = affectedArea;
        this.severity = severity;
        this.stage = stage;
        if (visibility != null) {
            this.visibility = visibility;
        }
        this.description = description;
        this.safetyAcknowledged = safetyAcknowledged;
        this.firstObservedAt = firstObservedAt;
        this.analysisStatus = analysisStatus;
    }
}
