package com.dwell.domain.cases.enums;

public enum CaseStage {
    LOGGED,
    AWAITING_RESPONSE,
    RESPONSE_OVERDUE,
    FOLLOW_UP_SENT,
    FOLLOW_UP_OVERDUE,
    SCHEDULING,
    REPAIR_SCHEDULED,
    REPAIR_DAY,
    REPAIR_IN_PROGRESS,
    LANDLORD_REFUSED,
    LANDLORD_BLAME,
    REPORTED_311,
    HPD_INSPECTION,
    VIOLATION_UNRESOLVED,
    SELF_REPAIR,
    CLAIM_SENT,
    INSURANCE_CLAIM,
    RESOLVED,
    RECURRED
}
