package com.dwell.domain.cases.enums;

public enum CaseEventType {
    CASE_CREATED,
    EVIDENCE_ADDED,
    NOTICE_SENT,
    FOLLOW_UP_SENT,
    RESPONSE_OVERDUE,
    LANDLORD_REPLIED,
    SCHEDULING,
    REPAIR_SCHEDULED,
    REPAIR_VISITED,
    LANDLORD_REFUSED,
    LANDLORD_BLAME,
    COMPLAINT_311_FILED,
    HPD_INSPECTION_SCHEDULED,
    VIOLATION_ISSUED,
    SELF_REPAIR_STARTED,
    CLAIM_SENT,
    INSURANCE_CLAIM_FILED,
    REPAIR_VERIFIED,
    RESOLVED,
    RECURRED
}
