-- All domain tables from the ERD (https://www.erdcloud.com/d/i94cCpMKsExKmiKT4)

CREATE EXTENSION IF NOT EXISTS vector;

-- users: align with the ERD
ALTER TABLE users RENAME COLUMN password TO password_hash;
ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL;
ALTER TABLE users RENAME COLUMN created_date TO created_at;
ALTER TABLE users RENAME COLUMN modified_date TO modified_at;
ALTER TABLE users ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE users ALTER COLUMN modified_at SET NOT NULL;
ALTER TABLE users ALTER COLUMN role TYPE VARCHAR(20);
ALTER TABLE users
    ADD COLUMN first_name         VARCHAR(50)  NOT NULL,
    ADD COLUMN last_name          VARCHAR(50)  NOT NULL,
    ADD COLUMN preferred_language VARCHAR(10)  NOT NULL,
    ADD COLUMN profile_image_key  VARCHAR(255),
    ADD COLUMN nickname           VARCHAR(30) UNIQUE,
    ADD COLUMN auth_provider      VARCHAR(10)  NOT NULL DEFAULT 'LOCAL',
    ADD COLUMN provider_id        VARCHAR(255),
    ADD CONSTRAINT uk_users_provider UNIQUE (auth_provider, provider_id);

CREATE TABLE refresh_token
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP    NOT NULL,
    revoked_at TIMESTAMP,
    created_at TIMESTAMP    NOT NULL
);

CREATE TABLE device
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    push_token VARCHAR(255) NOT NULL UNIQUE,
    platform   VARCHAR(20)  NOT NULL,
    created_at TIMESTAMP    NOT NULL
);

-- Building

CREATE TABLE building
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bbl           VARCHAR(10)  NOT NULL UNIQUE,
    street        VARCHAR(255) NOT NULL,
    city          VARCHAR(50)  NOT NULL,
    state         VARCHAR(2)   NOT NULL,
    zip           VARCHAR(10)  NOT NULL,
    hpd_synced_at TIMESTAMP,
    created_at    TIMESTAMP    NOT NULL
);

CREATE TABLE user_place
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT      NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    building_id       BIGINT      NOT NULL REFERENCES building (id),
    unit              VARCHAR(20) NOT NULL,
    floor             INT,
    unit_line         VARCHAR(10),
    lease_in_own_name BOOLEAN     NOT NULL,
    landlord_name     VARCHAR(100),
    landlord_phone    VARCHAR(20),
    created_at        TIMESTAMP   NOT NULL,
    modified_at       TIMESTAMP   NOT NULL
);

CREATE TABLE hpd_violation
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_id      BIGINT       NOT NULL REFERENCES building (id),
    record_type      VARCHAR(20)  NOT NULL,
    hpd_violation_id VARCHAR(20)  NOT NULL,
    issue_type       VARCHAR(20)  NOT NULL,
    category         VARCHAR(100) NOT NULL,
    status           VARCHAR(10)  NOT NULL,
    violation_class  VARCHAR(2),
    reported_at      DATE         NOT NULL,
    closed_at        DATE,
    CONSTRAINT uk_hpd_violation_record UNIQUE (record_type, hpd_violation_id)
);

CREATE TABLE building_insight
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_id          BIGINT      NOT NULL UNIQUE REFERENCES building (id),
    avg_days_to_resolve  INT,
    avg_response_days    DECIMAL(4, 1),
    no_response_rate     INT,
    landlord_risk        VARCHAR(20),
    data_source          VARCHAR(20) NOT NULL,
    computed_at          TIMESTAMP   NOT NULL
);

CREATE TABLE building_signal
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_id       BIGINT      NOT NULL REFERENCES building (id),
    issue_category    VARCHAR(30) NOT NULL,
    scope             VARCHAR(30) NOT NULL,
    floor_from        INT,
    floor_to          INT,
    report_count      INT         NOT NULL,
    window_days       INT         NOT NULL,
    insight           JSONB,
    guided_inspection JSONB,
    confidence        VARCHAR(10),
    breakdown         JSONB,
    computed_at       TIMESTAMP   NOT NULL
);

-- Case

CREATE TABLE cases
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_number         VARCHAR(20)  NOT NULL,
    user_id             BIGINT       NOT NULL REFERENCES users (id),
    building_id         BIGINT REFERENCES building (id),
    unit                VARCHAR(20),
    title               VARCHAR(100) NOT NULL,
    issue_category      VARCHAR(30)  NOT NULL,
    issue_detail        VARCHAR(30)  NOT NULL,
    issue_detail_other  VARCHAR(50),
    issue_type          VARCHAR(20)  NOT NULL,
    location            VARCHAR(20)  NOT NULL,
    location_other      VARCHAR(50),
    sub_location        VARCHAR(20),
    affected_area       VARCHAR(20)  NOT NULL,
    severity            VARCHAR(10)  NOT NULL,
    stage               VARCHAR(30)  NOT NULL,
    visibility          VARCHAR(10)  NOT NULL DEFAULT 'PRIVATE',
    description         VARCHAR(500),
    safety_acknowledged BOOLEAN      NOT NULL DEFAULT FALSE,
    first_observed_at   DATE,
    resolved_at         TIMESTAMP,
    analysis_status     VARCHAR(10)  NOT NULL,
    ai_analysis         JSONB,
    summary             JSONB,
    summary_updated_at  TIMESTAMP,
    next_action_type    VARCHAR(30),
    next_action         JSONB,
    deleted_at          TIMESTAMP,
    created_at          TIMESTAMP    NOT NULL,
    modified_at         TIMESTAMP    NOT NULL,
    CONSTRAINT uk_cases_user_case_number UNIQUE (user_id, case_number)
);

CREATE TABLE inspection_result
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT      NOT NULL REFERENCES users (id),
    building_id    BIGINT      NOT NULL REFERENCES building (id),
    case_id        BIGINT REFERENCES cases (id) ON DELETE SET NULL,
    signal_id      BIGINT REFERENCES building_signal (id) ON DELETE SET NULL,
    issue_category VARCHAR(30) NOT NULL,
    outcome        VARCHAR(20) NOT NULL,
    symptoms       JSONB       NOT NULL,
    created_at     TIMESTAMP   NOT NULL
);

CREATE TABLE case_event
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id     BIGINT      NOT NULL REFERENCES cases (id) ON DELETE CASCADE,
    type        VARCHAR(30) NOT NULL,
    occurred_at TIMESTAMP   NOT NULL,
    title       JSONB,
    ref_type    VARCHAR(20),
    ref_id      BIGINT,
    payload     JSONB,
    alert       BOOLEAN     NOT NULL DEFAULT FALSE
);

CREATE TABLE case_checklist_item
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id     BIGINT       NOT NULL REFERENCES cases (id) ON DELETE CASCADE,
    text        VARCHAR(255) NOT NULL,
    text_native TEXT,
    checked     BOOLEAN      NOT NULL DEFAULT FALSE,
    source      VARCHAR(10)  NOT NULL,
    sort_order  INT          NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    modified_at TIMESTAMP    NOT NULL
);

CREATE TABLE case_report
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id          BIGINT    NOT NULL REFERENCES cases (id) ON DELETE CASCADE,
    narrative        TEXT      NOT NULL,
    pdf_key          VARCHAR(255),
    evidence_zip_key VARCHAR(255),
    created_at       TIMESTAMP NOT NULL
);

CREATE TABLE reminder
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id     BIGINT      NOT NULL REFERENCES cases (id) ON DELETE CASCADE,
    type        VARCHAR(30) NOT NULL,
    fire_at     TIMESTAMP   NOT NULL,
    fired_at    TIMESTAMP,
    canceled_at TIMESTAMP,
    created_at  TIMESTAMP   NOT NULL
);

-- Evidence / File

CREATE TABLE evidence
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id              BIGINT      NOT NULL REFERENCES cases (id) ON DELETE CASCADE,
    user_id              BIGINT      NOT NULL REFERENCES users (id),
    evidence_code        VARCHAR(10) NOT NULL,
    media_type           VARCHAR(10) NOT NULL,
    phase                VARCHAR(20) NOT NULL DEFAULT 'INITIAL',
    location             VARCHAR(20) NOT NULL,
    location_detail      VARCHAR(100),
    sub_location         VARCHAR(20),
    description          VARCHAR(500),
    description_language VARCHAR(10),
    analysis_status      VARCHAR(10) NOT NULL,
    title                VARCHAR(100),
    issue_type           VARCHAR(20),
    severity             VARCHAR(10),
    reasons              JSONB,
    quality_checks       JSONB,
    progression          VARCHAR(10),
    progression_reason   JSONB,
    analyzed_at          TIMESTAMP,
    deleted_at           TIMESTAMP,
    created_at           TIMESTAMP   NOT NULL,
    CONSTRAINT uk_evidence_user_code UNIQUE (user_id, evidence_code)
);

CREATE TABLE repair_verification
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id            BIGINT      NOT NULL REFERENCES cases (id) ON DELETE CASCADE,
    before_evidence_id BIGINT      NOT NULL REFERENCES evidence (id) ON DELETE CASCADE,
    after_evidence_id  BIGINT      NOT NULL REFERENCES evidence (id) ON DELETE CASCADE,
    analysis_status    VARCHAR(10) NOT NULL,
    verdict            VARCHAR(20),
    headline           JSONB,
    summary            JSONB,
    checks             JSONB,
    disclaimer         JSONB,
    confirmed_at       TIMESTAMP,
    created_at         TIMESTAMP   NOT NULL
);

CREATE TABLE file
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id    VARCHAR(20)  NOT NULL UNIQUE,
    user_id      BIGINT       NOT NULL REFERENCES users (id),
    evidence_id  BIGINT REFERENCES evidence (id) ON DELETE SET NULL,
    purpose      VARCHAR(20)  NOT NULL DEFAULT 'EVIDENCE',
    media_type   VARCHAR(10)  NOT NULL,
    mime_type    VARCHAR(50)  NOT NULL,
    size_bytes   BIGINT       NOT NULL,
    duration_sec INT,
    storage_key  VARCHAR(255) NOT NULL,
    sha256       VARCHAR(64)  NOT NULL,
    captured_at  TIMESTAMP,
    quality_ok   BOOLEAN,
    created_at   TIMESTAMP    NOT NULL
);

-- Notice

CREATE TABLE notice
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id            BIGINT      NOT NULL REFERENCES cases (id) ON DELETE CASCADE,
    type               VARCHAR(10) NOT NULL,
    body_en            TEXT        NOT NULL,
    mirror_native      TEXT        NOT NULL,
    citations          JSONB       NOT NULL,
    retaliation_notice JSONB,
    body               TEXT,
    channel            VARCHAR(10),
    sent_at            TIMESTAMP,
    sla_due_at         TIMESTAMP,
    created_at         TIMESTAMP   NOT NULL
);

CREATE TABLE landlord_response
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id            BIGINT    NOT NULL REFERENCES cases (id) ON DELETE CASCADE,
    raw_text           TEXT      NOT NULL,
    sender_name        VARCHAR(100),
    received_at        TIMESTAMP NOT NULL,
    intent             VARCHAR(20),
    headline           JSONB,
    explanation        JSONB,
    translation_native TEXT,
    repair_date        DATE,
    repair_time        VARCHAR(20),
    repaired_by        VARCHAR(100),
    confirmed_at       TIMESTAMP,
    created_at         TIMESTAMP NOT NULL
);

-- Notification

CREATE TABLE notification
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    case_id     BIGINT REFERENCES cases (id) ON DELETE CASCADE,
    building_id BIGINT REFERENCES building (id),
    type        VARCHAR(30) NOT NULL,
    title       JSONB       NOT NULL,
    body        JSONB,
    read_at     TIMESTAMP,
    created_at  TIMESTAMP   NOT NULL
);

-- Assistant

CREATE TABLE conversation
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type       VARCHAR(10) NOT NULL,
    case_id    BIGINT REFERENCES cases (id) ON DELETE CASCADE,
    created_at TIMESTAMP   NOT NULL
);

-- One conversation per case
CREATE UNIQUE INDEX uk_conversation_case ON conversation (case_id) WHERE type = 'CASE';

CREATE TABLE message
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT      NOT NULL REFERENCES conversation (id) ON DELETE CASCADE,
    role            VARCHAR(10) NOT NULL,
    content         TEXT        NOT NULL,
    citations       JSONB,
    cards           JSONB,
    quick_replies   JSONB,
    attachments     JSONB,
    created_at      TIMESTAMP   NOT NULL
);

CREATE TABLE assistant_action
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT      NOT NULL UNIQUE REFERENCES message (id) ON DELETE CASCADE,
    type       VARCHAR(30) NOT NULL,
    choices    JSONB       NOT NULL,
    chosen     VARCHAR(20),
    payload    JSONB,
    created_at TIMESTAMP   NOT NULL
);

-- Legal RAG

CREATE TABLE legal_document
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label        VARCHAR(100) NOT NULL UNIQUE,
    title        VARCHAR(255),
    url          VARCHAR(500) NOT NULL,
    jurisdiction VARCHAR(20)  NOT NULL,
    created_at   TIMESTAMP    NOT NULL
);

CREATE TABLE legal_chunk
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT       NOT NULL REFERENCES legal_document (id) ON DELETE CASCADE,
    content     TEXT         NOT NULL,
    embedding   VECTOR(1024) NOT NULL,
    created_at  TIMESTAMP    NOT NULL
);

-- Community

CREATE TABLE post
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_id BIGINT        NOT NULL REFERENCES building (id),
    user_id     BIGINT REFERENCES users (id) ON DELETE SET NULL,
    board       VARCHAR(10)   NOT NULL,
    title       VARCHAR(100)  NOT NULL,
    content     VARCHAR(1000) NOT NULL,
    floor_band  VARCHAR(10)   NOT NULL,
    created_at  TIMESTAMP     NOT NULL,
    modified_at TIMESTAMP     NOT NULL
);

CREATE TABLE post_image
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    BIGINT    NOT NULL REFERENCES post (id) ON DELETE CASCADE,
    file_id    BIGINT    NOT NULL UNIQUE REFERENCES file (id),
    sort_order INT       NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE tag
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(30) NOT NULL UNIQUE,
    created_at TIMESTAMP   NOT NULL
);

CREATE TABLE post_tag
(
    post_id BIGINT NOT NULL REFERENCES post (id) ON DELETE CASCADE,
    tag_id  BIGINT NOT NULL REFERENCES tag (id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, tag_id)
);

CREATE TABLE reply
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    BIGINT       NOT NULL REFERENCES post (id) ON DELETE CASCADE,
    user_id    BIGINT REFERENCES users (id) ON DELETE SET NULL,
    content    VARCHAR(500) NOT NULL,
    floor_band VARCHAR(10)  NOT NULL,
    created_at TIMESTAMP    NOT NULL
);

CREATE TABLE post_like
(
    post_id    BIGINT    NOT NULL REFERENCES post (id) ON DELETE CASCADE,
    user_id    BIGINT    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (post_id, user_id)
);
